version: 2
jobs:
  test_string_calculator_kata:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: mvn clean test

workflows:
  version: 2
  run_tests_for_katas:
    jobs:
      - test_string_calculator_kata